### ISSUE TITLE
panic: invalid page type: 21: 10

### ISSUE THREAD

**Issue by Gorgeous-Patrick** [safing/portmaster#1073]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:
Portmaster core cannot start. I got the following error erport:

```
230126 18:53:06.257 er/storage:146 ▶ WARN 001 updates: failed to verify signature of index stable.json: failed to read signature file: open /opt/safing/portmaster/updates/stable.json.sig: no such file or directory
===== Error Report =====
Message: panic: invalid page type: 21: 10
Timestamp: 2023-01-26 18:53:06.260788701 -0500 EST m=+0.159546286
ModuleName: updates
TaskName: start module
TaskType: module-control
Severity: panic
PanicValue: invalid page type: 21: 10
StackTrace:

goroutine 210 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/safing/portbase/modules.(*Module).NewPanicError(0xc0002ae500, {0xe16ca4, 0xc}, {0xe1b62d, 0xe}, {0xcf7500?, 0xc000bef270})
	/home/user/git/safing/portbase/modules/error.go:61 +0x94
github.com/safing/portbase/modules.(*Module).runCtrlFn.func1()
	/home/user/git/safing/portbase/modules/worker.go:160 +0x71
panic({0xcf7500, 0xc000bef270})
	/usr/local/go/src/runtime/panic.go:884 +0x212
go.etcd.io/bbolt.(*Cursor).search(0xc0011a3bc0, {0xc000eeb330, 0xf, 0x10}, 0x0?)
	/home/user/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/cursor.go:250 +0x299
go.etcd.io/bbolt.(*Cursor).searchPage(0xc0011a3bc0, {0xc000eeb330, 0xf, 0x10}, 0x40d01f?)
	/home/user/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/cursor.go:308 +0x166
go.etcd.io/bbolt.(*Cursor).search(0xc0011a3bc0, {0xc000eeb330, 0xf, 0x10}, 0xc0011a3b40?)
	/home/user/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/cursor.go:265 +0x1db
go.etcd.io/bbolt.(*Cursor).seek(0xc0011a3bc0, {0xc000eeb330?, 0x10?, 0x0?})
	/home/user/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/cursor.go:159 +0x48
go.etcd.io/bbolt.(*Bucket).Put(0xc000b385c0, {0xc000eeb330, 0xf, 0x10}, {0xc0005a8000, 0x5ea7, 0x5ea7})
	/home/user/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/bucket.go:295 +0x114
github.com/safing/portbase/database/storage/bbolt.(*BBolt).Put.func1(0x30?)
	/home/user/git/safing/portbase/database/storage/bbolt/bbolt.go:116 +0xa9
go.etcd.io/bbolt.(*DB).Update(0xc000263c20?, 0xc0011a3ce8)
	/home/user/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:741 +0x82
github.com/safing/portbase/database/storage/bbolt.(*BBolt).Put(0xc0004c41b0, {0xfa70b0, 0xc000263c20})
	/home/user/git/safing/portbase/database/storage/bbolt/bbolt.go:115 +0x8d
github.com/safing/portbase/database.(*Controller).Put(0xc000294f80, {0xfa70b0, 0xc000263c20})
	/home/user/git/safing/portbase/database/controller.go:140 +0xc8
github.com/safing/portbase/database.(*Interface).Put(0xc0001b8ff0, {0xfa70b0, 0xc000263c20})
	/home/user/git/safing/portbase/database/interface.go:303 +0x2a5
github.com/safing/portmaster/updates.(*Versions).save(0xc000263c20?)
	/home/user/git/safing/portmaster/updates/export.go:121 +0x4f
github.com/safing/portmaster/updates.initVersionExport()
	/home/user/git/safing/portmaster/updates/export.go:102 +0x25
github.com/safing/portmaster/updates.start()
	/home/user/git/safing/portmaster/updates/main.go:152 +0x46a
github.com/safing/portbase/modules.(*Module).runCtrlFn(0xc00072efd0?, {0xe16ca4?, 0xc000172a00?}, 0xe1374a?)
	/home/user/git/safing/portbase/modules/worker.go:167 +0xda
github.com/safing/portbase/modules.(*Module).runCtrlFnWithTimeout.func1()
	/home/user/git/safing/portbase/modules/worker.go:135 +0x32
created by github.com/safing/portbase/modules.(*Module).runCtrlFnWithTimeout
	/home/user/git/safing/portbase/modules/worker.go:134 +0x10c


===== End of Report =====
===== Error Report =====
Message: panic: invalid page type: 21: 10
Timestamp: 2023-01-26 18:53:06.260976486 -0500 EST m=+0.159734010
ModuleName: updates
TaskName: start module
TaskType:
Severity: error
PanicValue: %!s(<nil>)
StackTrace:

goroutine 200 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/safing/portbase/modules.(*Module).NewErrorMessage(0xc0002ae500, {0xe16ca4, 0xc}, {0xf97b80?, 0xc000cd4070?})
	/home/user/git/safing/portbase/modules/error.go:48 +0x49
github.com/safing/portbase/modules.startModules()
	/home/user/git/safing/portbase/modules/start.go:200 +0x1de
github.com/safing/portbase/modules.ManageModules()
	/home/user/git/safing/portbase/modules/mgmt.go:112 +0xda
github.com/safing/portbase/modules/subsystems.(*Manager).handleConfigChanges(0xe15924?, {0xc?, 0xe1a9c3?})
	/home/user/git/safing/portbase/modules/subsystems/registry.go:253 +0x205
github.com/safing/portbase/modules/subsystems.(*Manager).CheckConfig(0xb?, {0xf9d538?, 0xc000614740?})
	/home/user/git/safing/portbase/modules/subsystems/registry.go:196 +0x25
github.com/safing/portbase/modules.(*Module).runWorker(0x0?, {0xe3abec?, 0xc000086f18?}, 0x988425?)
	/home/user/git/safing/portbase/modules/worker.go:128 +0x93
github.com/safing/portbase/modules.(*Module).RunWorker(0x75eba0?, {0xe3abec?, 0xe16ca4?}, 0xc?)
	/home/user/git/safing/portbase/modules/worker.go:52 +0x77
github.com/safing/portbase/modules.(*Module).StartWorker.func1()
	/home/user/git/safing/portbase/modules/worker.go:27 +0x4a
created by github.com/safing/portbase/modules.(*Module).StartWorker
	/home/user/git/safing/portbase/modules/worker.go:26 +0xac


===== End of Report =====
```

**What did you expect to happen?**:

Kernel should start normally.

**How did you reproduce it?**:

```/opt/safing/portmaster/updates/linux_amd64/core/portmaster-core_v1-0-4 --data /opt/safing/portmaster```

**Debug Information**:

**Comment by Raphty** [comment]
Hey @Gorgeous-Patrick I see you are running linux, what distro is this?

**Comment by Gorgeous-Patrick** [comment]
Any updates?

**Comment by Gorgeous-Patrick** [comment]
Hello?

**Comment by dhaavi** [comment]
:notes: I just came to say hello :notes:

Seriously, though, we are a small team and things take time.

This crash comes from the database `bbolt` we are using. I just prepared a release with an update to this library (bbolt v1.3.7). You can check it out tomorrow in the Beta release channel.
Maybe it'll work then.

If you want to help, you can check if this (kind of) bug was already reported to https://github.com/etcd-io/bbolt and what its status is.
