### ISSUE TITLE
Windows 11 arm support

### ISSUE THREAD

**Issue by alfredonodo** [safing/portmaster#1080]
Hi,
I installed the latest version 1.0.6 of portmaster on windows 11 arm which has an integrated emulator for x86_64 software. When portmaster starts I get the following error:

`Failed to start module: interception: could not start windows kext: failed to open driver: "\\.\PortmasterKext" The system cannot find the file specified.
`
```
The only useful log that I found on `%PROGRAMDATA%\Safing\Portmaster\logs` is the following:
NJ{"Created":1675350116,"Modified":1675350116,"Expires":1677942116,"Deleted":0}S
executing core/portmaster-core.exe version 1.0.6 on windows amd64
===== Error Report =====
Message: interception: could not start windows kext: failed to open driver: "\\\\.\\PortmasterKext" The system cannot find the file specified.
Timestamp: 2023-02-02 16:01:57.1745406 +0100 CET m=+0.742346401
ModuleName: interception
TaskName: start module
TaskType: 
Severity: error
PanicValue: %!s(<nil>)
StackTrace:

goroutine 197 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/safing/portbase/modules.(*Module).NewErrorMessage(0xc000526500, {0xdff551, 0xc}, {0xf8f960?, 0xc000656af0?})
	/home/user/git/safing/portbase/modules/error.go:48 +0x49
github.com/safing/portbase/modules.startModules()
	/home/user/git/safing/portbase/modules/start.go:200 +0x1de
github.com/safing/portbase/modules.ManageModules()
	/home/user/git/safing/portbase/modules/mgmt.go:112 +0xda
github.com/safing/portbase/modules/subsystems.(*Manager).handleConfigChanges(0x2d704926?, {0x2d704901?, 0xc000689ea8?})
	/home/user/git/safing/portbase/modules/subsystems/registry.go:253 +0x205
github.com/safing/portbase/modules/subsystems.(*Manager).CheckConfig(0x30?, {0xf955f8?, 0xc00022d300?})
	/home/user/git/safing/portbase/modules/subsystems/registry.go:196 +0x25
github.com/safing/portbase/modules.(*Module).runWorker(0xc000689ef0?, {0xe26948?, 0x77c001?}, 0xc000689f98?)
	/home/user/git/safing/portbase/modules/worker.go:128 +0x93
github.com/safing/portbase/modules.(*Module).RunWorker(0xc0000a0020?, {0xe26948?, 0x77c340?}, 0xc000113260?)
	/home/user/git/safing/portbase/modules/worker.go:52 +0x77
github.com/safing/portbase/modules.(*Module).StartWorker.func1()
	/home/user/git/safing/portbase/modules/worker.go:27 +0x4a
created by github.com/safing/portbase/modules.(*Module).StartWorker
	/home/user/git/safing/portbase/modules/worker.go:26 +0xac


===== End of Report =====
```

**Comment by dhaavi** [comment]
This is because you can't emulate the kernel driver, which is loaded into the kernel.

We will need to compile that (and everything else) specifically for arm. I will have to check how many more parts are still missing to get this to work.

Also, I think this is a dupe. Please look for the other issue and link it.

**Comment by alfredonodo** [comment]
Right. I am not sure if you are referring to this [issue](https://github.com/safing/portmaster/issues/1079). There is a closed issue about [PortmasterKext](https://github.com/safing/portmaster/issues/200).

**Comment by Alxshakycrwr187** [comment]
Well....we stepped in to help the Lad out.
Alex, N co defendants... distance. The price to pay is deeper than a pocket

**Comment by lepras** [comment]
hi, any hope for this?
