### ISSUE TITLE
Panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by rootsquid** [safing/portmaster#1163]
**What happened**:
I installed debian sid a few days ago and then portmaster. It worked there without any problems. For other reasons I had to reinstall debian sid again and did the same first steps as I installed portmaster. Unfortunately I get the message "Starting module interception failed" "Failed to start module: panic: runtime error: invalid memory address or nil pointer dereference"

**What did you expect to happen?**:
Portmaster works as before at any time after installation with dpkg -i portmaster.deb

**How did you reproduce it?**:
Just opening the Portmaster UI to see this error appears

**Debug Information**:

Paste debug information below:

```
Apr 10 00:11:18 username systemd[1]: Started portmaster.service - Portmaster by Safing.
Apr 10 00:11:18 username portmaster-start[7016]: [control] 2023/04/09 22:11:18 starting /opt/safing/portmaster/updates/linux_amd64/core/portmaster-core_v1-0-11 --data /opt/safing/portmaster
Apr 10 00:11:18 username portmaster-start[7016]: 230410 00:11:18.477 ▶ BOF
Apr 10 00:11:24 username portmaster-start[7016]: 230410 00:11:24.471 les/worker:098 ▶ ERRO 001 resolver: service-worker name record delayed cache writer failed (1): could not start database cache (type bbolt): timeout - restarting in 2s
Apr 10 00:11:26 username portmaster-start[7016]: ===== Error Report =====
Apr 10 00:11:26 username portmaster-start[7016]: Message: panic: runtime error: invalid memory address or nil pointer dereference
Apr 10 00:11:26 username portmaster-start[7016]: Timestamp: 2023-04-10 00:11:26.787932477 +0200 CEST m=+8.324022876
Apr 10 00:11:26 username portmaster-start[7016]: ModuleName: interception
Apr 10 00:11:26 username portmaster-start[7016]: TaskName: start module
Apr 10 00:11:26 username portmaster-start[7016]: TaskType: module-control
Apr 10 00:11:26 username portmaster-start[7016]: Severity: panic
Apr 10 00:11:26 username portmaster-start[7016]: PanicValue: runtime error: invalid memory address or nil pointer dereference
Apr 10 00:11:26 username portmaster-start[7016]: StackTrace:
Apr 10 00:11:26 username portmaster-start[7016]: goroutine 400 [running]:
Apr 10 00:11:26 username portmaster-start[7016]: runtime/debug.Stack()
Apr 10 00:11:26 username portmaster-start[7016]:         /usr/local/go/src/runtime/debug/stack.go:24 +0x65
Apr 10 00:11:26 username portmaster-start[7016]: github.com/safing/portbase/modules.(*Module).NewPanicError(0xc0004ec640, {0xe40019, 0xc}, {0xe44d06, 0xe}, {0xd49a60?, 0x15bdb10})
Apr 10 00:11:26 username portmaster-start[7016]:         /home/user/git/safing/portbase/modules/error.go:61 +0x94
Apr 10 00:11:26 username portmaster-start[7016]: github.com/safing/portbase/modules.(*Module).runCtrlFn.func1()
Apr 10 00:11:26 username portmaster-start[7016]:         /home/user/git/safing/portbase/modules/worker.go:162 +0x71
Apr 10 00:11:26 username portmaster-start[7016]: panic({0xd49a60, 0x15bdb10})
Apr 10 00:11:26 username portmaster-start[7016]:         /usr/local/go/src/runtime/panic.go:884 +0x212
Apr 10 00:11:26 username portmaster-start[7016]: github.com/florianl/go-conntrack.(*Nfct).Close(0xfd4220?)
Apr 10 00:11:26 username portmaster-start[7016]:         /home/user/go/pkg/mod/github.com/florianl/go-conntrack@v0.4.0/conntrack.go:100 +0x18
Apr 10 00:11:26 username portmaster-start[7016]: github.com/safing/portmaster/firewall/interception/nfq.TeardownNFCT(...)
...skipping...
Apr 10 13:20:26 username portmaster-start[8718]: github.com/safing/portbase/modules.(*Module).NewErrorMessage(0xc0004ee640, {0xe40019, 0xc}, {0xfd4480?, 0xc0008b2000?})
Apr 10 13:20:26 username portmaster-start[8718]:         /home/user/git/safing/portbase/modules/error.go:48 +0x49
Apr 10 13:20:26 username portmaster-start[8718]: github.com/safing/portbase/modules.startModules()
Apr 10 13:20:26 username portmaster-start[8718]:         /home/user/git/safing/portbase/modules/start.go:200 +0x1de
Apr 10 13:20:26 username portmaster-start[8718]: github.com/safing/portbase/modules.ManageModules()
Apr 10 13:20:26 username portmaster-start[8718]:         /home/user/git/safing/portbase/modules/mgmt.go:112 +0xda
Apr 10 13:20:26 username portmaster-start[8718]: github.com/safing/portbase/modules/subsystems.(*Manager).handleConfigChanges(0xe3c35e?, {0xb?, 0xe3ebfd?})
Apr 10 13:20:26 username portmaster-start[8718]:         /home/user/git/safing/portbase/modules/subsystems/registry.go:253 +0x205
Apr 10 13:20:26 username portmaster-start[8718]: github.com/safing/portbase/modules/subsystems.(*Manager).CheckConfig(0xe?, {0xfd9ed8?, 0xc00061e680?})
Apr 10 13:20:26 username portmaster-start[8718]:         /home/user/git/safing/portbase/modules/subsystems/registry.go:196 +0x25
Apr 10 13:20:26 username portmaster-start[8718]: github.com/safing/portbase/modules.(*Module).runWorker(0x0?, {0xe64f1d?, 0xc000595718?}, 0x98f4e5?)
Apr 10 13:20:26 username portmaster-start[8718]:         /home/user/git/safing/portbase/modules/worker.go:130 +0x93
Apr 10 13:20:26 username portmaster-start[8718]: github.com/safing/portbase/modules.(*Module).RunWorker(0x760b80?, {0xe64f1d?, 0xe40019?}, 0xc?)
Apr 10 13:20:26 username portmaster-start[8718]:         /home/user/git/safing/portbase/modules/worker.go:52 +0x77
Apr 10 13:20:26 username portmaster-start[8718]: github.com/safing/portbase/modules.(*Module).StartWorker.func1()
Apr 10 13:20:26 username portmaster-start[8718]:         /home/user/git/safing/portbase/modules/worker.go:27 +0x4a
Apr 10 13:20:26 username portmaster-start[8718]: created by github.com/safing/portbase/modules.(*Module).StartWorker
Apr 10 13:20:26 username portmaster-start[8718]:         /home/user/git/safing/portbase/modules/worker.go:26 +0xac
Apr 10 13:20:26 username portmaster-start[8718]: ===== End of Report =====
Apr 10 13:20:26 username portmaster-start[8718]: 230410 13:20:26.095 dules/mgmt:114 ▶ WARN 001 modules: could not start module interception: panic: runtime error: invalid memory address or nil pointer dereference
Apr 10 13:20:26 username portmaster-start[8718]: 230410 13:20:26.095 les/worker:034 ▶ ERRO 003 subsystems: worker initial subsystem configuration failed: modules: could not start module interception: panic: runtime error: invalid memory>
Apr 10 13:20:27 username portmaster-start[8718]: 230410 13:20:27.210 v/location:254 ▶ WARN 005 netenv: failed to get geolocation data of 2003:e9:f12:8500:a3e5:9b78:75c6:4efb (from interface): geoip database not available
Apr 10 13:20:28 username portmaster-start[8718]: 230410 13:20:28.999 v/location:301 ▶ WARN 007 netenv: failed to get IPv4 device location from traceroute: did not receive any actionable ICMP reply
...skipping...
Apr 10 13:20:26 username portmaster-start[8718]: github.com/safing/portbase/modules.(*Module).NewErrorMessage(0xc0004ee640, {0xe40019, 0xc}, {0xfd4480?, 0xc0008b2000?})
Apr 10 13:20:26 username portmaster-start[8718]:         /home/user/git/safing/portbase/modules/error.go:48 +0x49
Apr 10 13:20:26 username portmaster-start[8718]: github.com/safing/portbase/modules.startModules()
Apr 10 13:20:26 username portmaster-start[8718]:         /home/user/git/safing/portbase/modules/start.go:200 +0x1de
Apr 10 13:20:26 username portmaster-start[8718]: github.com/safing/portbase/modules.ManageModules()
Apr 10 13:20:26 username portmaster-start[8718]:         /home/user/git/safing/portbase/modules/mgmt.go:112 +0xda
Apr 10 13:20:26 username portmaster-start[8718]: github.com/safing/portbase/modules/subsystems.(*Manager).handleConfigChanges(0xe3c35e?, {0xb?, 0xe3ebfd?})
Apr 10 13:20:26 username portmaster-start[8718]:         /home/user/git/safing/portbase/modules/subsystems/registry.go:253 +0x205
Apr 10 13:20:26 username portmaster-start[8718]: github.com/safing/portbase/modules/subsystems.(*Manager).CheckConfig(0xe?, {0xfd9ed8?, 0xc00061e680?})
Apr 10 13:20:26 username portmaster-start[8718]:         /home/user/git/safing/portbase/modules/subsystems/registry.go:196 +0x25
Apr 10 13:20:26 username portmaster-start[8718]: github.com/safing/portbase/modules.(*Module).runWorker(0x0?, {0xe64f1d?, 0xc000595718?}, 0x98f4e5?)
Apr 10 13:20:26 username portmaster-start[8718]:         /home/user/git/safing/portbase/modules/worker.go:130 +0x93
Apr 10 13:20:26 username portmaster-start[8718]: github.com/safing/portbase/modules.(*Module).RunWorker(0x760b80?, {0xe64f1d?, 0xe40019?}, 0xc?)
Apr 10 13:20:26 username portmaster-start[8718]:         /home/user/git/safing/portbase/modules/worker.go:52 +0x77
Apr 10 13:20:26 username portmaster-start[8718]: github.com/safing/portbase/modules.(*Module).StartWorker.func1()
Apr 10 13:20:26 username portmaster-start[8718]:         /home/user/git/safing/portbase/modules/worker.go:27 +0x4a
Apr 10 13:20:26 username portmaster-start[8718]: created by github.com/safing/portbase/modules.(*Module).StartWorker
Apr 10 13:20:26 username portmaster-start[8718]:         /home/user/git/safing/portbase/modules/worker.go:26 +0xac
Apr 10 13:20:26 username portmaster-start[8718]: ===== End of Report =====
Apr 10 13:20:26 username portmaster-start[8718]: 230410 13:20:26.095 dules/mgmt:114 ▶ WARN 001 modules: could not start module interception: panic: runtime error: invalid memory address or nil pointer dereference
Apr 10 13:20:26 username portmaster-start[8718]: 230410 13:20:26.095 les/worker:034 ▶ ERRO 003 subsystems: worker initial subsystem configuration failed: modules: could not start module interception: panic: runtime error: invalid memory>
Apr 10 13:20:27 username portmaster-start[8718]: 230410 13:20:27.210 v/location:254 ▶ WARN 005 netenv: failed to get geolocation data of 2003:e9:f12:8500:a3e5:9b78:75c6:4efb (from interface): geoip database not available
Apr 10 13:20:28 username portmaster-start[8718]: 230410 13:20:28.999 v/location:301 ▶ WARN 007 netenv: failed to get IPv4 device location from traceroute: did not receive any actionable ICMP reply
...skipping...
Apr 10 13:20:26 username portmaster-start[8718]: github.com/safing/portbase/modules.(*Module).NewErrorMessage(0xc0004ee640, {0xe40019, 0xc}, {0xfd4480?, 0xc0008b2000?})
Apr 10 13:20:26 username portmaster-start[8718]:         /home/user/git/safing/portbase/modules/error.go:48 +0x49
Apr 10 13:20:26 username portmaster-start[8718]: github.com/safing/portbase/modules.startModules()
Apr 10 13:20:26 username portmaster-start[8718]:         /home/user/git/safing/portbase/modules/start.go:200 +0x1de
Apr 10 13:20:26 username portmaster-start[8718]: github.com/safing/portbase/modules.ManageModules()
Apr 10 13:20:26 username portmaster-start[8718]:         /home/user/git/safing/portbase/modules/mgmt.go:112 +0xda
Apr 10 13:20:26 username portmaster-start[8718]: github.com/safing/portbase/modules/subsystems.(*Manager).handleConfigChanges(0xe3c35e?, {0xb?, 0xe3ebfd?})
Apr 10 13:20:26 username portmaster-start[8718]:         /home/user/git/safing/portbase/modules/subsystems/registry.go:253 +0x205
Apr 10 13:20:26 username portmaster-start[8718]: github.com/safing/portbase/modules/subsystems.(*Manager).CheckConfig(0xe?, {0xfd9ed8?, 0xc00061e680?})
Apr 10 13:20:26 username portmaster-start[8718]:         /home/user/git/safing/portbase/modules/subsystems/registry.go:196 +0x25
Apr 10 13:20:26 username portmaster-start[8718]: github.com/safing/portbase/modules.(*Module).runWorker(0x0?, {0xe64f1d?, 0xc000595718?}, 0x98f4e5?)
Apr 10 13:20:26 username portmaster-start[8718]:         /home/user/git/safing/portbase/modules/worker.go:130 +0x93
Apr 10 13:20:26 username portmaster-start[8718]: github.com/safing/portbase/modules.(*Module).RunWorker(0x760b80?, {0xe64f1d?, 0xe40019?}, 0xc?)
Apr 10 13:20:26 username portmaster-start[8718]:         /home/user/git/safing/portbase/modules/worker.go:52 +0x77
Apr 10 13:20:26 username portmaster-start[8718]: github.com/safing/portbase/modules.(*Module).StartWorker.func1()
Apr 10 13:20:26 username portmaster-start[8718]:         /home/user/git/safing/portbase/modules/worker.go:27 +0x4a
Apr 10 13:20:26 username portmaster-start[8718]: created by github.com/safing/portbase/modules.(*Module).StartWorker
Apr 10 13:20:26 username portmaster-start[8718]:         /home/user/git/safing/portbase/modules/worker.go:26 +0xac
Apr 10 13:20:26 username portmaster-start[8718]: ===== End of Report =====
Apr 10 13:20:26 username portmaster-start[8718]: 230410 13:20:26.095 dules/mgmt:114 ▶ WARN 001 modules: could not start module interception: panic: runtime error: invalid memory address or nil pointer dereference
Apr 10 13:20:26 username portmaster-start[8718]: 230410 13:20:26.095 les/worker:034 ▶ ERRO 003 subsystems: worker initial subsystem configuration failed: modules: could not start module interception: panic: runtime error: invalid memory>
Apr 10 13:20:27 username portmaster-start[8718]: 230410 13:20:27.210 v/location:254 ▶ WARN 005 netenv: failed to get geolocation data of 2003:e9:f12:8500:a3e5:9b78:75c6:4efb (from interface): geoip database not available
Apr 10 13:20:28 username portmaster-start[8718]: 230410 13:20:28.999 v/location:301 ▶ WARN 007 netenv: failed to get IPv4 device location from traceroute: did not receive any actionable ICMP reply
...skipping...
Apr 10 13:20:26 username portmaster-start[8718]: github.com/safing/portbase/modules.(*Module).NewErrorMessage(0xc0004ee640, {0xe40019, 0xc}, {0xfd4480?, 0xc0008b2000?})
Apr 10 13:20:26 username portmaster-start[8718]:         /home/user/git/safing/portbase/modules/error.go:48 +0x49
Apr 10 13:20:26 username portmaster-start[8718]: github.com/safing/portbase/modules.startModules()
Apr 10 13:20:26 username portmaster-start[8718]:         /home/user/git/safing/portbase/modules/start.go:200 +0x1de
Apr 10 13:20:26 username portmaster-start[8718]: github.com/safing/portbase/modules.ManageModules()
Apr 10 13:20:26 username portmaster-start[8718]:         /home/user/git/safing/portbase/modules/mgmt.go:112 +0xda
Apr 10 13:20:26 username portmaster-start[8718]: github.com/safing/portbase/modules/subsystems.(*Manager).handleConfigChanges(0xe3c35e?, {0xb?, 0xe3ebfd?})
Apr 10 13:20:26 username portmaster-start[8718]:         /home/user/git/safing/portbase/modules/subsystems/registry.go:253 +0x205
Apr 10 13:20:26 username portmaster-start[8718]: github.com/safing/portbase/modules/subsystems.(*Manager).CheckConfig(0xe?, {0xfd9ed8?, 0xc00061e680?})
Apr 10 13:20:26 username portmaster-start[8718]:         /home/user/git/safing/portbase/modules/subsystems/registry.go:196 +0x25
Apr 10 13:20:26 username portmaster-start[8718]: github.com/safing/portbase/modules.(*Module).runWorker(0x0?, {0xe64f1d?, 0xc000595718?}, 0x98f4e5?)
Apr 10 13:20:26 username portmaster-start[8718]:         /home/user/git/safing/portbase/modules/worker.go:130 +0x93
Apr 10 13:20:26 username portmaster-start[8718]: github.com/safing/portbase/modules.(*Module).RunWorker(0x760b80?, {0xe64f1d?, 0xe40019?}, 0xc?)
Apr 10 13:20:26 username portmaster-start[8718]:         /home/user/git/safing/portbase/modules/worker.go:52 +0x77
Apr 10 13:20:26 username portmaster-start[8718]: github.com/safing/portbase/modules.(*Module).StartWorker.func1()
Apr 10 13:20:26 username portmaster-start[8718]:         /home/user/git/safing/portbase/modules/worker.go:27 +0x4a
Apr 10 13:20:26 username portmaster-start[8718]: created by github.com/safing/portbase/modules.(*Module).StartWorker
Apr 10 13:20:26 username portmaster-start[8718]:         /home/user/git/safing/portbase/modules/worker.go:26 +0xac
Apr 10 13:20:26 username portmaster-start[8718]: ===== End of Report =====
Apr 10 13:20:26 username portmaster-start[8718]: 230410 13:20:26.095 dules/mgmt:114 ▶ WARN 001 modules: could not start module interception: panic: runtime error: invalid memory address or nil pointer dereference
Apr 10 13:20:26 username portmaster-start[8718]: 230410 13:20:26.095 les/worker:034 ▶ ERRO 003 subsystems: worker initial subsystem configuration failed: modules: could not start module interception: panic: runtime error: invalid memory>
Apr 10 13:20:27 username portmaster-start[8718]: 230410 13:20:27.210 v/location:254 ▶ WARN 005 netenv: failed to get geolocation data of 2003:e9:f12:8500:a3e5:9b78:75c6:4efb (from interface): geoip database not available
Apr 10 13:20:28 username portmaster-start[8718]: 230410 13:20:28.999 v/location:301 ▶ WARN 007 netenv: failed to get IPv4 device location from traceroute: did not receive any actionable ICMP reply



Additional logs can be found here:
- Linux: `/opt/safing/portmaster/logs/core/error.log :

NJ{"Created":1681125625,"Modified":1681125625,"Expires":1683717625,"Deleted":0}S
executing core/portmaster-core version 1.0.11 on linux amd64
===== Error Report =====
Message: panic: runtime error: invalid memory address or nil pointer dereference
Timestamp: 2023-04-10 13:20:26.095065337 +0200 CEST m=+0.174188886
ModuleName: interception
TaskName: start module
TaskType: module-control
Severity: panic
PanicValue: runtime error: invalid memory address or nil pointer dereference
StackTrace:

goroutine 262 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/safing/portbase/modules.(*Module).NewPanicError(0xc0004ee640, {0xe40019, 0xc}, {0xe44d06, 0xe}, {0xd49a60?, 0x15bdb10})
	/home/user/git/safing/portbase/modules/error.go:61 +0x94
github.com/safing/portbase/modules.(*Module).runCtrlFn.func1()
	/home/user/git/safing/portbase/modules/worker.go:162 +0x71
panic({0xd49a60, 0x15bdb10})
	/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/florianl/go-conntrack.(*Nfct).Close(0xfd4220?)
	/home/user/go/pkg/mod/github.com/florianl/go-conntrack@v0.4.0/conntrack.go:100 +0x18
github.com/safing/portmaster/firewall/interception/nfq.TeardownNFCT(...)
	/home/user/git/safing/portmaster/firewall/interception/nfq/conntrack.go:30
github.com/safing/portmaster/firewall/interception.DeactivateNfqueueFirewall()
	/home/user/git/safing/portmaster/firewall/interception/nfqueue_linux.go:175 +0x11c
github.com/safing/portmaster/firewall/interception.StopNfqueueInterception()
	/home/user/git/safing/portmaster/firewall/interception/nfqueue_linux.go:313 +0xc9
github.com/safing/portmaster/firewall/interception.stop(...)
	/home/user/git/safing/portmaster/firewall/interception/interception_linux.go:16
github.com/safing/portmaster/firewall/interception.Stop(...)
	/home/user/git/safing/portmaster/firewall/interception/interception.go:50
github.com/safing/portmaster/firewall/interception.StartNfqueueInterception(0xc00003f4a0)
	/home/user/git/safing/portmaster/firewall/interception/nfqueue_linux.go:260 +0x92
github.com/safing/portmaster/firewall/interception.start(...)
	/home/user/git/safing/portmaster/firewall/interception/interception_linux.go:11
github.com/safing/portmaster/firewall/interception.Start()
	/home/user/git/safing/portmaster/firewall/interception/interception.go:39 +0xe5
github.com/safing/portmaster/firewall.interceptionStart()
	/home/user/git/safing/portmaster/firewall/interception.go:180 +0xcb
github.com/safing/portbase/modules.(*Module).runCtrlFn(0x0?, {0xe40019?, 0x0?}, 0x0?)
	/home/user/git/safing/portbase/modules/worker.go:169 +0xda
github.com/safing/portbase/modules.(*Module).runCtrlFnWithTimeout.func1()
	/home/user/git/safing/portbase/modules/worker.go:137 +0x32
created by github.com/safing/portbase/modules.(*Module).runCtrlFnWithTimeout
	/home/user/git/safing/portbase/modules/worker.go:136 +0x10c


===== End of Report =====
===== Error Report =====
Message: panic: runtime error: invalid memory address or nil pointer dereference
Timestamp: 2023-04-10 13:20:26.095447764 +0200 CEST m=+0.174571293
ModuleName: interception
TaskName: start module
TaskType: 
Severity: error
PanicValue: %!s(<nil>)
StackTrace:

goroutine 197 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/safing/portbase/modules.(*Module).NewErrorMessage(0xc0004ee640, {0xe40019, 0xc}, {0xfd4480?, 0xc0008b2000?})
	/home/user/git/safing/portbase/modules/error.go:48 +0x49
github.com/safing/portbase/modules.startModules()
	/home/user/git/safing/portbase/modules/start.go:200 +0x1de
github.com/safing/portbase/modules.ManageModules()
	/home/user/git/safing/portbase/modules/mgmt.go:112 +0xda
github.com/safing/portbase/modules/subsystems.(*Manager).handleConfigChanges(0xe3c35e?, {0xb?, 0xe3ebfd?})
	/home/user/git/safing/portbase/modules/subsystems/registry.go:253 +0x205
github.com/safing/portbase/modules/subsystems.(*Manager).CheckConfig(0xe?, {0xfd9ed8?, 0xc00061e680?})
	/home/user/git/safing/portbase/modules/subsystems/registry.go:196 +0x25
github.com/safing/portbase/modules.(*Module).runWorker(0x0?, {0xe64f1d?, 0xc000595718?}, 0x98f4e5?)
	/home/user/git/safing/portbase/modules/worker.go:130 +0x93
github.com/safing/portbase/modules.(*Module).RunWorker(0x760b80?, {0xe64f1d?, 0xe40019?}, 0xc?)
	/home/user/git/safing/portbase/modules/worker.go:52 +0x77
github.com/safing/portbase/modules.(*Module).StartWorker.func1()
	/home/user/git/safing/portbase/modules/worker.go:27 +0x4a
created by github.com/safing/portbase/modules.(*Module).StartWorker
	/home/user/git/safing/portbase/modules/worker.go:26 +0xac


===== End of Report =====
```

**Comment by Shr4pNull** [comment]
I have encountered the same issue. Can we expect an updated .deb file soon?

Kind regards.

**Comment by dhaavi** [comment]
The fix is now in the Beta Release Channel: https://wiki.safing.io/en/FAQ/SwitchReleaseChannel

Even with the error, you should be able to change the release channel and auto-update to Beta.

**Comment by rootsquid** [comment]
Thank you for the fix! 
Portmaster works for me without any issues now
