### ISSUE TITLE
Error in loading public network login page

### ISSUE THREAD

**Issue by TheArctesian** [safing/portmaster#1216]
**What happened**:
Hello I've been using portmaster for around 3 months now and have loved it so far, apart from this. I am at a public Library in Hong Kong, when I connect to the public network gnome-shell helper portal comes up but returns the failed to resolve name servers. This issue disappears when I turn postmaster off. I poked around in the settings trying to fix it but to try and toggle things on and off and change DNS servers but still nothing worked till I turned it off. 

**How did you reproduce it?**:
Connecting to a public network with a login page (might be this specific edge case)
**Debug Information**:
```python
   2   │ executing core/portmaster-core version 1.0.13 on linux amd64
   3   │ ===== Error Report =====
   4   │ Message: panic: runtime error: integer divide by zero
   5   │ Timestamp: 2023-05-14 11:03:29.527687045 +0800 CST m=+200.122891217
   6   │ ModuleName: resolver
   7   │ TaskName: suggest using stale cache
   8   │ TaskType: task
   9   │ Severity: panic
  10   │ PanicValue: runtime error: integer divide by zero
  11   │ StackTrace:
  12   │
  13   │ goroutine 4461 [running]:
  14   │ runtime/debug.Stack()
  15   │     /usr/local/go/src/runtime/debug/stack.go:24 +0x65
  16   │ github.com/safing/portbase/modules.(*Module).NewPanicError(0xc000272580, {0xe7c82e, 0x19}, {0x
       │ e51496, 0x4}, {0xd67b80?, 0x15de670})
  17   │     /home/user/git/safing/portbase/modules/error.go:61 +0x94
  18   │ github.com/safing/portbase/modules.(*Task).executeWithLocking.func1()
  19   │     /home/user/git/safing/portbase/modules/tasks.go:351 +0x85
  20   │ panic({0xd67b80, 0x15de670})
  21   │     /usr/local/go/src/runtime/panic.go:884 +0x213
  22   │ github.com/safing/portmaster/resolver.getSlowQueriesSensorValue(...)
  23   │     /home/user/git/safing/portmaster/resolver/metrics.go:35
  24   │ github.com/safing/portmaster/resolver.suggestUsingStaleCacheTask({0xc000273600?, 0xc002c09f28?
       │ }, 0xc002c09fd0?)
  25   │     /home/user/git/safing/portmaster/resolver/metrics.go:72 +0x50f
  26   │ github.com/safing/portbase/modules.(*Task).executeWithLocking(0xc000757830)
  27   │     /home/user/git/safing/portbase/modules/tasks.go:385 +0xbb
  28   │ created by github.com/safing/portbase/modules.(*Task).runWithLocking
  29   │     /home/user/git/safing/portbase/modules/tasks.go:331 +0x305
```

<!-- 
Journalctl -b
```
May 14 11:03:24 arctesiansframework portmaster-start[637]: 230514 11:03:24.613 nameserver:286 ▶ WARN 155 nameserver: failed to resolve www.google.com.A: query failed: failed to connect to Cloudflare (dot://cloudflare-dns.com:853#config): dial tcp :44526->1.1.1.2:853: i/o timeout
May 14 11:03:27 arctesiansframework portmaster-start[637]: 230514 11:03:27.615 nameserver:286 ▶ WARN 157 nameserver: failed to resolve www.google.com.AAAA: query failed: failed to connect to Cloudflare (dot://cloudflare-dns.com:853#config): dial tcp :47323->1.1.1.2:853: i/o timeout
May 14 11:03:29 arctesiansframework portmaster-start[637]: 230514 11:03:29.527 ules/tasks:353 ▶ ERRO 159 resolver: task suggest using stale cache panicked: runtime error: integer divide by zero
May 14 11:03:29 arctesiansframework portmaster-start[637]: goroutine 4461 [running]:
May 14 11:03:29 arctesiansframework portmaster-start[637]: runtime/debug.Stack()
May 14 11:03:29 arctesiansframework portmaster-start[637]:         /usr/local/go/src/runtime/debug/stack.go:24 +0x65
May 14 11:03:29 arctesiansframework portmaster-start[637]: github.com/safing/portbase/modules.(*Module).NewPanicError(0xc000272580, {0xe7c82e, 0x19}, {0xe51496, 0x4}, {0xd67b80?, 0x15de670})
May 14 11:03:29 arctesiansframework portmaster-start[637]:         /home/user/git/safing/portbase/modules/error.go:61 +0x94
May 14 11:03:29 arctesiansframework portmaster-start[637]: github.com/safing/portbase/modules.(*Task).executeWithLocking.func1()
May 14 11:03:29 arctesiansframework portmaster-start[637]:         /home/user/git/safing/portbase/modules/tasks.go:351 +0x85
May 14 11:03:29 arctesiansframework portmaster-start[637]: panic({0xd67b80, 0x15de670})
May 14 11:03:29 arctesiansframework portmaster-start[637]:         /usr/local/go/src/runtime/panic.go:884 +0x213
May 14 11:03:29 arctesiansframework portmaster-start[637]: github.com/safing/portmaster/resolver.getSlowQueriesSensorValue(...)
May 14 11:03:29 arctesiansframework portmaster-start[637]:         /home/user/git/safing/portmaster/resolver/metrics.go:35
May 14 11:03:29 arctesiansframework portmaster-start[637]: github.com/safing/portmaster/resolver.suggestUsingStaleCacheTask({0xc000273600?, 0xc002c09f28?}, 0xc002c09fd0?)
May 14 11:03:29 arctesiansframework portmaster-start[637]:         /home/user/git/safing/portmaster/resolver/metrics.go:72 +0x50f
May 14 11:03:29 arctesiansframework portmaster-start[637]: github.com/safing/portbase/modules.(*Task).executeWithLocking(0xc000757830)
May 14 11:03:29 arctesiansframework portmaster-start[637]:         /home/user/git/safing/portbase/modules/tasks.go:385 +0xbb
May 14 11:03:29 arctesiansframework portmaster-start[637]: created by github.com/safing/portbase/modules.(*Task).runWithLocking
May 14 11:03:29 arctesiansframework portmaster-start[637]:         /home/user/git/safing/portbase/modules/tasks.go:331 +0x305
May 14 11:03:29 arctesiansframework portmaster-start[637]: ===== Error Report =====
May 14 11:03:29 arctesiansframework portmaster-start[637]: Message: panic: runtime error: integer divide by zero
May 14 11:03:29 arctesiansframework portmaster-start[637]: Timestamp: 2023-05-14 11:03:29.527687045 +0800 CST m=+200.122891217
May 14 11:03:29 arctesiansframework portmaster-start[637]: ModuleName: resolver
May 14 11:03:29 arctesiansframework portmaster-start[637]: TaskName: suggest using stale cache
May 14 11:03:29 arctesiansframework portmaster-start[637]: TaskType: task
May 14 11:03:29 arctesiansframework portmaster-start[637]: Severity: panic
May 14 11:03:29 arctesiansframework portmaster-start[637]: PanicValue: runtime error: integer divide by zero
May 14 11:03:29 arctesiansframework portmaster-start[637]: StackTrace:
May 14 11:03:29 arctesiansframework portmaster-start[637]: goroutine 4461 [running]:
May 14 11:03:29 arctesiansframework portmaster-start[637]: runtime/debug.Stack()
May 14 11:03:29 arctesiansframework portmaster-start[637]:         /usr/local/go/src/runtime/debug/stack.go:24 +0x65
May 14 11:03:29 arctesiansframework portmaster-start[637]: github.com/safing/portbase/modules.(*Module).NewPanicError(0xc000272580, {0xe7c82e, 0x19}, {0xe51496, 0x4}, {0xd67b80?, 0x15de670})
May 14 11:03:29 arctesiansframework portmaster-start[637]:         /home/user/git/safing/portbase/modules/error.go:61 +0x94
May 14 11:03:29 arctesiansframework portmaster-start[637]: github.com/safing/portbase/modules.(*Task).executeWithLocking.func1()
May 14 11:03:29 arctesiansframework portmaster-start[637]:         /home/user/git/safing/portbase/modules/tasks.go:351 +0x85
May 14 11:03:29 arctesiansframework portmaster-start[637]: panic({0xd67b80, 0x15de670})
May 14 11:03:29 arctesiansframework portmaster-start[637]:         /usr/local/go/src/runtime/panic.go:884 +0x213
May 14 11:03:29 arctesiansframework portmaster-start[637]: github.com/safing/portmaster/resolver.getSlowQueriesSensorValue(...)
May 14 11:03:29 arctesiansframework portmaster-start[637]:         /home/user/git/safing/portmaster/resolver/metrics.go:35
May 14 11:03:29 arctesiansframework portmaster-start[637]: github.com/safing/portmaster/resolver.suggestUsingStaleCacheTask({0xc000273600?, 0xc002c09f28?}, 0xc002c09fd0?)
May 14 11:03:29 arctesiansframework portmaster-start[637]:         /home/user/git/safing/portmaster/resolver/metrics.go:72 +0x50f
May 14 11:03:29 arctesiansframework portmaster-start[637]: github.com/safing/portbase/modules.(*Task).executeWithLocking(0xc000757830)
May 14 11:03:29 arctesiansframework portmaster-start[637]:         /home/user/git/safing/portbase/modules/tasks.go:385 +0xbb
May 14 11:03:29 arctesiansframework portmaster-start[637]: created by github.com/safing/portbase/modules.(*Task).runWithLocking
May 14 11:03:29 arctesiansframework portmaster-start[637]:         /home/user/git/safing/portbase/modules/tasks.go:331 +0x305
May 14 11:03:29 arctesiansframework portmaster-start[637]: ===== End of Report =====
```
->

**Comment by Raphty** [comment]
captive portals should trigger an notification in Portmaster and you can click on it there
