### ISSUE TITLE
Windows 11, error "The Portmaster Core Service is not running", but the service itself is enabled.

### ISSUE THREAD

**Issue by GuiltHC** [safing/portmaster#1247]
**What happened**:
Windows 11, error "The Portmaster Core Service is not running", but the service itself is enabled. 

**What did you expect to happen?**:
I was expecting the app would move into a running state.

**How did you reproduce it?**:
Reinstalled applications and rebooted the PC several times.

**Comment by Raphty** [comment]
With so little info there is sadly nothing we can do, Portmaster runs well on windows 11, based on user surveys.

**Comment by aaronsvk** [comment]
Probably the same issue in my case, here is the log:

```
executing core/portmaster-core.exe version 1.3.0 on windows amd64
===== Error Report =====
Message: failed to create in-memory database: failed to prepare database: failed to attach history database: sqlite: step: SQL logic error: invalid uri authority: C:\ProgramData\Safing\Portmaster\databases
Timestamp: 2023-07-24 17:46:15.847515 +0200 CEST m=+0.013269001
ModuleName: netquery
TaskName: prep module
TaskType: 
Severity: error
PanicValue: %!s(<nil>)
StackTrace:

goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/safing/portbase/modules.(*Module).NewErrorMessage(0xc0002ed1e0, {0x13ef46e, 0xb}, {0x15612e0?, 0xc0006907c0?})
	/home/user/git/safing/portbase/modules/error.go:48 +0x49
github.com/safing/portbase/modules.prepareModules()
	/home/user/git/safing/portbase/modules/start.go:152 +0x1b8
github.com/safing/portbase/modules.Start()
	/home/user/git/safing/portbase/modules/start.go:68 +0x18e
github.com/safing/portbase/run.Run()
	/home/user/git/safing/portbase/run/main.go:34 +0x2b
main.main()
	/home/user/git/safing/portmaster/cmds/portmaster-core/main.go:42 +0x171


===== End of Report =====
CRITICAL ERROR: failed to prep module netquery: failed to create in-memory database: failed to prepare database: failed to attach history database: sqlite: step: SQL logic error: invalid uri authority: C:\ProgramData\Safing\Portmaster\databases
```

**Comment by dhaavi** [comment]
Fixed in https://github.com/safing/portmaster/releases/tag/v1.3.1.
